version: '3.9'
services:
  air_quality_db_test:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=$DB_NAME
    container_name: air_quality_db_test

  air_quality_api_test:
    build:
      context: .
      target: build
    container_name: air_quality_api_test
    command: npm run test
    env_file:
      - .env
    environment:
      - PORT=$PORT
    ports:
      - 8080:$PORT
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - air_quality_db
