version: '3.9'
services:
  air_quality_db:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=$DB_NAME
    container_name: air_quality_db

  air_quality_api:
    build:
      context: .
      target: build
    container_name: air_quality_api
    command: npm run start:dev
    env_file:
      - .env
    environment:
      - PORT=$PORT
      - NODE_ENV=development
    ports:
      - 8080:$PORT
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - air_quality_db
